minVersion: "2.21.2"
noMerge: false
changelog:
  policy: auto
statusProvider:
  name: github
  config:
    contexts:
      - test_job
      - build_website
artifactProvider:
  name: github
  config:
    artifacts:
      Build & Test:
        - action-package
        - gh-pages
targets:
  - name: github
  - name: gh-pages
