import type { AggregatedTestResults } from "../types/test-results.js";

export class PRCommentFormatter {
	/**
	 * Format test results as a markdown comment for PRs
	 */
	formatComment(results: AggregatedTestResults): string {
		const lines: string[] = [];

		// Header
		lines.push("## Test Results 🧪");
		lines.push("");

		// Summary line with emoji indicators
		const passEmoji = results.passedTests > 0 ? "✅" : "";
		const failEmoji = results.failedTests > 0 ? "❌" : "";
		const skipEmoji = results.skippedTests > 0 ? "⏭️" : "";

		const summaryParts: string[] = [];

		if (passEmoji) {
			summaryParts.push(`${passEmoji} **${results.passedTests} passed**`);
		}
		if (failEmoji) {
			summaryParts.push(`${failEmoji} **${results.failedTests} failed**`);
		}
		if (skipEmoji) {
			summaryParts.push(`${skipEmoji} **${results.skippedTests} skipped**`);
		}

		// Add total and pass rate
		summaryParts.push(`**Total: ${results.totalTests}**`);
		summaryParts.push(`**Pass Rate: ${results.passRate}%**`);

		lines.push(summaryParts.join(" | "));
		lines.push("");

		// Execution time
		lines.push(
			`⏱️ **Execution Time:** ${this.formatTime(results.totalTime)}`,
		);
		lines.push("");

		// Show failed tests if any
		if (results.failedTests > 0 && results.failedTestCases.length > 0) {
			lines.push("### ❌ Failed Tests");
			lines.push("");

			for (const { suiteName, testCase } of results.failedTestCases) {
				// Test header
				lines.push(`#### \`${testCase.name}\``);
				lines.push(`**File:** \`${testCase.classname}\``);

				if (suiteName && suiteName !== testCase.classname) {
					lines.push(`**Suite:** \`${suiteName}\``);
				}

				if (testCase.failure) {
					lines.push(`**Error:** ${testCase.failure.message}`);
					lines.push("");

					// Stack trace in collapsible details
					if (testCase.failure.content) {
						lines.push("<details>");
						lines.push("<summary>Stack Trace</summary>");
						lines.push("");
						lines.push("```");
						lines.push(testCase.failure.content.trim());
						lines.push("```");
						lines.push("");
						lines.push("</details>");
						lines.push("");
					}
				}
			}
		} else if (results.failedTests === 0) {
			// Success message
			lines.push("### ✅ All Tests Passed!");
			lines.push("");
			lines.push("Great job! All tests are passing successfully.");
			lines.push("");
		}

		// Footer
		lines.push("---");
		lines.push("*Generated by Codecov Action*");

		return lines.join("\n");
	}

	/**
	 * Format execution time in a human-readable way
	 */
	private formatTime(seconds: number): string {
		if (seconds < 1) {
			return `${Math.round(seconds * 1000)}ms`;
		}
		if (seconds < 60) {
			return `${seconds.toFixed(2)}s`;
		}
		const minutes = Math.floor(seconds / 60);
		const remainingSeconds = seconds % 60;
		return `${minutes}m ${remainingSeconds.toFixed(0)}s`;
	}

	/**
	 * Generate a unique identifier for the comment
	 * This helps identify comments created by this action
	 */
	static getCommentIdentifier(): string {
		return "<!-- codecov-action-test-results -->";
	}

	/**
	 * Add identifier to comment body
	 */
	addIdentifier(comment: string): string {
		return `${PRCommentFormatter.getCommentIdentifier()}\n${comment}`;
	}
}

